### PR TITLE
Add the encryption to LDAP config

### PR DESCRIPTION
**Pull request by cherweg**

### CODE REVIEW

**Comment by mkristian** [comment]
thanx a lot - should push a release I guess ?

**Comment by cherweg** [comment]
A release and a new Version of the gem would be great.

Regards
Christian
Am 23.01.2015 11:34 schrieb "Christian Meier" <notifications@github.com>:

**Comment by mkristian** [comment]
just pushed dm-ldap-adapter-0.4.8.gem

**Comment by cherweg** [comment]
Great. Thank you.

regards
christian

2015-01-28 8:29 GMT+01:00 Christian Meier <notifications@github.com>:

> just pushed dm-ldap-adapter-0.4.8.gem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkristian/dm-ldap-adapter/pull/20#issuecomment-71792214>
> .
>



-- 
Christian Herweg
Harckestwiete 3
22844 Norderstedt
Tel. 040/50090374
E-Maill: christian.herweg@gmail.com

**Pull request merged**
